const {
  listarTodasDividas,
  criarNovaDivida,
  updateDividas,
  deleteDivida
} = require('./controllers/dividaController')

const express = require('express')
const app = express()
const port = 3000

app.use(express.json())

// Buscar - listarTodasDividas()
app.get('/', (req, res) => {
  try {
    const resultado = listarTodasDividas()
    res.json({
      mensagem: 'Pesquisada concluÃ­da.',
      dados: resultado
    })
  } catch (error) {
    console.error('Erro ao processar dÃ­vida:', error)
    res.status(500).json({ error: 'Falha interna ao processar dados.' })
  }
})

// Cadastrar - criarNovaDivida
app.post('/cadastrar', (req, res) => {
  try {
    const resultado = criarNovaDivida()
    res.json({
      mensagem: `DÃ­vida cadastrada com sucesso.`,
      dados: resultado
    })
  } catch (error) {
    console.error('Erro ao cadastrar dÃ­vida:', error)
    res.status(500).json({ error: 'Falha interna ao processar dados.' })
  }
})

// Update
app.put('/dividas/:id', (req, res) => {
   try {
    const resultado = updateDividas()
    res.json({
      mensagem: `DÃ­vida atualizada com sucesso.`,
      dados: resultado
    })
  } catch (error) {
    console.error('Erro ao atualizar dÃ­vida:', error)
    res.status(500).json({ error: 'Falha interna ao processar dados.' })
  }
})

// Delete
app.delete('/dividas/:id', (req, res) => {
  try {
    const resultado = deleteDivida()
    res.json({
      mensagem: `DÃ­vida deletada com sucesso.`,
      dados: resultado
    })
  } catch (error) {
    console.error('Erro ao deletar dÃ­vida:', error)
    res.status(500).json({ error: 'Falha interna ao processar dados.' })
  }
})

app.listen(port, () => console.log('Ta up ğŸš€'))
